---
kind: pipeline
name: default

steps:
  - name: composer
    image: joomlaprojects/docker-images:php8.3
    volumes:
      - name: composer-cache
        path: /tmp/composer-cache
    commands:
      - composer install --no-progress --ignore-platform-reqs

  - name: phpcs
    image: joomlaprojects/docker-images:php8.1
    depends_on: [ composer ]
    commands:
      - echo $(date)
      - ./vendor/bin/php-cs-fixer fix -vvv --dry-run --diff
      - ./vendor/bin/phpcs --extensions=php -p --standard=ruleset.xml src/
      - echo $(date)

  - name: prepare_tests
    depends_on: [ composer ]
    image: joomlaprojects/docker-images:cypress8.2
    commands:
      - vendor/bin/robo build
      - curl https://joomla.org/latest -L --output joomla.zip
      - mkdir joomla
      - cp joomla.zip joomla/joomla.zip
      - cd joomla
      - unzip joomla.zip

  - name: phpstan
    image: joomlaprojects/docker-images:php8.2
    depends_on: [ prepare_tests ]
    failure: ignore
    commands:
      - vendor/bin/phpstan

volumes:
  - name: composer-cache
    host:
      path: /tmp/composer-cache

---
kind: signature
hmac: 185a81743827fe02d6281724b30bdb25fb6e161f68d545483fa1924e61874b57

...
